### ISSUE TITLE
Red-reds

### ISSUE THREAD

**Issue by julianflowers** [PublicHealthEngland/fingertipsR#14]
Function to identity indicators and areas which are worse than comparators and trend is worsening. Suggested code based on latest indicator value

**Comment by julianflowers** [comment]
`r fingertips_red_red <- function(ProfileID = 26, AreaTypeID = 102){
  
  data <- fingertips_latest_data(ProfileID = ProfileID, AreaTypeID = AreaTypeID)
  
  data %>%
    filter(stringr::str_detect(RecentTrend, "worse"), ComparedtoEnglandvalueorpercentiles == "Worse")

  
}`

**Comment by sebastian-fox** [comment]
Added in 3530bcd
