### ISSUE TITLE
Can you try this - returns no data

### ISSUE THREAD

**Issue by julianflowers** [PublicHealthEngland/fingertipsR#16]
`ftips_data <- fingertips_data(ProfileID = 101, IndicatorID = 92344, AreaTypeID = 19)
`

**Comment by sebastian-fox** [comment]
See issue #13 - this is a bug. It is fixed in the current version of the package on GitHub and will be available in the next release. To get it working without reinstalling the package just include `inequalities = TRUE` in your statement

**Comment by julianflowers** [comment]
Cheers!
