### ISSUE TITLE
`profiles()` should probably return unique values

### ISSUE THREAD

**Issue by sebastian-fox** [PublicHealthEngland/fingertipsR#17]
Currently running `profiles()` returns a data frame with redundant combinations, e.g. 6 rows of `ProfileID == 8` and `ProfileName == "Adult Social Care"`
As a user, exploring data, I would find a non-redundant list easier to read. What do you think?

**Comment by sebastian-fox** [comment]
@simonthelwall - I don’t think there are any duplicated records? It looks like you may have only been looking at the first two fields and not seen the third and the fourth?

**Comment by julianflowers** [comment]
It returns the domains within each profile so records aren't duplicates but there is overlap with the indicators function which does the same plus the indicators
