### ISSUE TITLE
Has deprivation_decile() stopped working

### ISSUE THREAD

**Issue by simonthelwall** [PublicHealthEngland/fingertipsR#27]
Last time I tried to compile the paper, the function didn't pull in any data. I did:
`dep <- deprivation_decile(AreaTypeID = 102, Year = 2015)`
And got a zero length dataframe as a result

**Comment by sebastian-fox** [comment]
Thanks for this. I can see why it is returning a zero length dataframe but I don't understand why it ever returned a non zero length dataframe. I recommend updating your version to use the development version on GitHub, eg, `devtools::install_github("PublicHealthEngland/fingertipsR")` which will hopefully go live in the next couple of weeks - so shouldn't be a problem when the paper is submitted
