### ISSUE TITLE
latest_indicators()

### ISSUE THREAD

**Issue by sebastian-fox** [PublicHealthEngland/fingertipsR#5]
A function that returns the indicators included at the latest data release

**Comment by sebastian-fox** [comment]
This is being picked up in API changes

**Comment by sebastian-fox** [comment]
Julian has offered a function that he has created to deal with this too. SF to confirm timescales of API update with DF

**Comment by julianflowers** [comment]
`## Function to extract data frame of most recent data for each indicator for a given ProfileID(s) and AreaTypeID(s)

fingertips_latest_data <- function(ProfileID = 26, AreaTypeID = 102, inequalities = FALSE){
  require(dplyr)
  ind_test <- fingertips_data(ProfileID = ProfileID, AreaTypeID = AreaTypeID, inequalities = inequalities)
  ind_test <- ind_test %>% mutate(index = paste(IndicatorID, Timeperiod, Age, Sex))
  
  latest <- ind_test %>%
    group_by(IndicatorID, AreaType, Age, Sex) %>%
    do(tail(., 1)) 
 
  
  ind_test %>% filter(index %in% latest$index)
  
}`

**Comment by sebastian-fox** [comment]
Sortable time period field now retrieved in data extract (c6982d1977a6882450eabbcfd0f3f8c521f1b403)
